# единая точка входа для всех контейнеров
version: "3"

# имена сервисов контейнеров
services:
  api:
    build: ./api
    # запуск сценария из package.json
    command: npm run start
    # слева наружный порт контейнера справа внутренний порт приложения
    ports:
      - "3000:3000"