version: '3'

# только вновь записанные поля будут изменяться
#  а остальное будет как в docker-compose.yml
services:
  api:
    command: npm run dev
    # эта папка будет не пересобираться заново
    # слева это то что берем с папки 
    # и делаем симлинк внутри контейнера сохраняя состояние
    volumes:
      - ./api/src:/usr/src/app/src

  auth: 
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src
