# единая точка входа для всех контейнеров
version: "3"

# имена сервисов контейнеров
services:
  # сервис который работает с экспрессом
  api:
    build: ./api
    # запуск сценария из package.json
    command: npm run start
    # всегда перезапускаем контейнер за исключением случаев когда остановлен вручную
    restart: unless-stopped
    # слева наружный порт контейнера справа внутренний порт приложения
    ports:
      - "3000:3000"
    # переменные окружения которые мы можем пробросить внутри контейнера  
    environment:
      - PORT=3000
      - HOST=http://docker-template.ru
      # образец с 'mongodb://127.0.0.1:27017/api' просто локалхос меняем на хос образа монги
      - MONGO_URL=mongodb://db:27017/api
    depends_on:
      # запускаем его после запуска образа базы данных монго
      - db

  # сервис который работает с базой данных берем готовый образ
  db:
    image: mongo:latest